### ISSUE TITLE
cannot find module `webpack-sources`

### ISSUE THREAD

**Issue by joshwiens** [TheLarkInn/V8LazyParseWebpackPlugin#6]
```
> angular2-webpack-starter@5.1.1 build:prod /home/travis/build/AngularClass/angular2-webpack-starter
> webpack --config config/webpack.prod.js  --progress --profile --bail
Error: Cannot find module 'webpack-sources'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/v8-lazy-parse-webpack-plugin/V8LazyParsedFunctionModuleTemplatePlugin.js:5:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/v8-lazy-parse-webpack-plugin/V8LazyParsedFunctionModulePlugin.js:5:48)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/AngularClass/angular2-webpack-starter/node_modules/v8-lazy-parse-webpack-plugin/index.js:1:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
npm ERR! Linux 3.19.0-66-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.6.2/bin/node" "/home/travis/.nvm/versions/node/v4.6.2/bin/npm" "run" "build:prod"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.1.1 build:prod: `webpack --config config/webpack.prod.js  --progress --profile --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-webpack-starter@5.1.1 build:prod script 'webpack --config config/webpack.prod.js  --progress --profile --bail'.
npm ERR! This is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config config/webpack.prod.js  --progress --profile --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/AngularClass/angular2-webpack-starter/npm-debug.log

```
**Env:** Travis CI running on the Trusty ( non beta ) containers.
`webpack-sources` isn't resolving on node 4.x when `process.env.ENV = 'production'` and only on *nix. The same task works fine on OSX.

See [this travis run](https://travis-ci.org/AngularClass/angular2-webpack-starter/builds/178771050) for execution across all node versions. 

@TheLarkInn - If i get some time tomorrow, i'll take a look at this and see if I can figure out what the deal is.

**Comment by TheLarkInn** [comment]
Thanks for the report 🙏
